export const orderList = [
  {
    id: 1,
    clothImage: "/images/productIcons/shirt.jpg",
    clothType: "Shirts",
    description: "Lorem ipsum dolor sit amet consectetur.",
    itemName: "shirts",
    cost: 10,
  },
  {
    id: 2,
    clothImage: "/images/productIcons/tshirt.jpg",
    clothType: "T Shirts",
    description: "Lorem ipsum dolor sit amet consectetur.",
    itemName: "tShirts",
    cost: 5,
  },
  {
    id: 3,
    clothImage: "/images/productIcons/jeans.jpg",
    clothType: "Jeans",
    description: "Lorem ipsum dolor sit amet consectetur.",
    itemName: "tousers",
    cost: 15,
  },
  {
    id: 4,
    clothImage: "/images/productIcons/trouser.jpg",
    clothType: "Trousers",
    description: "Lorem ipsum dolor sit amet consectetur.",
    itemName: "tousers",
    cost: 20,
  },
  {
    id: 5,
    clothImage: "/images/productIcons/short.jpg",
    clothType: "Boxers",
    description: "Lorem ipsum dolor sit amet consectetur.",
    itemName: "boxers",
    cost: 10,
  },
  {
    id: 6,
    clothImage: "/images/productIcons/joggers.jpg",
    clothType: "Joggers",
    description: "Lorem ipsum dolor sit amet consectetur.",
    itemName: "joggers",
    cost: 30,
  },
  {
    id: 7,
    clothImage: "/images/productIcons/others.jpg",
    clothType: "Others",
    description: "Lorem ipsum dolor sit amet consectetur.",
    itemName: "others",
    cost: 20,
  },
];
